"""add_auth_url_and_config

Revision ID: 5ee71fadeffe
Revises: a5e390c35a3c
Create Date: 2026-08-22 09:45:02.189367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee71fadeffe'
down_revision: Union[str, Sequence[str], None] = 'a5e390c35a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('auth_url', sa.String(), nullable=True))
    op.add_column('onboardings', sa.Column('auth_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboardings', 'auth_config')
    op.drop_column('onboardings', 'auth_url')
    # ### end Alembic commands ###
