"""add merchant user sessions

Revision ID: 77d5736d01fa
Revises: 02e9b0c6085c
Create Date: 2026-08-29 01:04:34.902526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d5736d01fa'
down_revision: Union[str, Sequence[str], None] = '02e9b0c6085c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_ref', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('merchant_token_encrypted', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_merchant_customer', 'merchant_user_sessions', ['merchant_id', 'customer_ref'], unique=False)
    op.create_index(op.f('ix_merchant_user_sessions_merchant_id'), 'merchant_user_sessions', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_user_sessions_merchant_id'), table_name='merchant_user_sessions')
    op.drop_index('idx_merchant_customer', table_name='merchant_user_sessions')
    op.drop_table('merchant_user_sessions')
    # ### end Alembic commands ###
