"""refactor_auth_connection_columns

Revision ID: 87379f527e4f
Revises: 5ee71fadeffe
Create Date: 2026-08-22 09:48:03.022093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87379f527e4f'
down_revision: Union[str, Sequence[str], None] = '5ee71fadeffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('auth_enabled', sa.Boolean(), nullable=False))
    op.add_column('onboardings', sa.Column('auth_disabled_ack', sa.Boolean(), nullable=False))
    op.drop_column('onboardings', 'credential_value')
    op.drop_column('onboardings', 'auth_url')
    op.drop_column('onboardings', 'auth_method')
    op.drop_column('onboardings', 'auth_needed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('auth_needed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('onboardings', sa.Column('auth_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onboardings', sa.Column('auth_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onboardings', sa.Column('credential_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('onboardings', 'auth_disabled_ack')
    op.drop_column('onboardings', 'auth_enabled')
    # ### end Alembic commands ###
