"""create_onboarding_table

Revision ID: a5e390c35a3c
Revises: c90486873571
Create Date: 2026-08-22 01:03:20.026229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e390c35a3c'
down_revision: Union[str, Sequence[str], None] = 'c90486873571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboardings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('auth_needed', sa.Boolean(), nullable=False),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('credential_value', sa.String(), nullable=True),
    sa.Column('endpoints', sa.JSON(), nullable=False),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('ifsc', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_onboardings_user_id'), 'onboardings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboardings_user_id'), table_name='onboardings')
    op.drop_table('onboardings')
    # ### end Alembic commands ###
