"""add_metadata_to_conversation_messages

Revision ID: bf15785d778f
Revises: 312f57759028
Create Date: 2026-08-29 12:49:59.001311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf15785d778f'
down_revision: Union[str, Sequence[str], None] = '312f57759028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'metadata')
    # ### end Alembic commands ###
