"""add_individual_resource_configs

Revision ID: fbb7c8f8816f
Revises: 87379f527e4f
Create Date: 2026-08-22 10:20:00.389990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbb7c8f8816f'
down_revision: Union[str, Sequence[str], None] = '87379f527e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('products_config', sa.JSON(), nullable=True))
    op.add_column('onboardings', sa.Column('order_history_config', sa.JSON(), nullable=True))
    op.add_column('onboardings', sa.Column('customer_profile_config', sa.JSON(), nullable=True))
    op.add_column('onboardings', sa.Column('addresses_config', sa.JSON(), nullable=True))
    op.add_column('onboardings', sa.Column('create_order_config', sa.JSON(), nullable=True))
    op.drop_column('onboardings', 'endpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('endpoints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('onboardings', 'create_order_config')
    op.drop_column('onboardings', 'addresses_config')
    op.drop_column('onboardings', 'customer_profile_config')
    op.drop_column('onboardings', 'order_history_config')
    op.drop_column('onboardings', 'products_config')
    # ### end Alembic commands ###
